name: flutter_jukebox
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.3
  audio_video_progress_bar: ^1.0.1
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.2+1
  get_it: ^7.2.0
  hooks_riverpod: ^1.0.3
  just_audio: ^0.9.19
  provider: ^6.0.0
  rxdart: ^0.27.3
  state_notifier: ^0.7.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter  
  
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
